### ISSUE TITLE
3-2씬 제외하고 다 실행불가 오류뜹니다.

### ISSUE THREAD

**Issue by screat100** [G-Man-git/PROJECT-SS-2#17]
![image](https://user-images.githubusercontent.com/61044260/83637642-e5834a00-a5e2-11ea-8d73-329842a1bc24.png)

위와 같은 오류 발생하여 실행 및 해당씬으로 이동이 안됩니다

**Comment by grootnam** [comment]
건 컨트롤러 -> 샷 이펙트 재지정을 통해 해결

**Comment by screat100** [comment]
확인
