### ISSUE TITLE
특수방에서 인벤토리를 연 상태에서 E키를 누를 때 정지가 풀림

### ISSUE THREAD

**Issue by screat100** [G-Man-git/PROJECT-SS-2#54]
- 환경 : 1-3, 3-5 등 특수 방에서, 인벤토리를 연 상태로
- 조건 : E키 입력
- 현상 : 인벤토리 연 상태에서 적용되는 게임 정지가 풀림

**Comment by grootnam** [comment]
인벤토리가 활성화된 상태에선 E키를 눌러도 게임 정지 안풀리게 수정
