### ISSUE TITLE
인벤토리를 연 상태에서 Maker 등을 열 수 없어야 함

### ISSUE THREAD

**Issue by screat100** [G-Man-git/PROJECT-SS-2#55]
- 인벤토리 연 상태에서 e키 입력하여 Maker 등을 열 수 없어야 하는데 열림
- [E interation] 표기도 함께 등장함 ==> 없애야 함

**Comment by grootnam** [comment]
Maker 주변에서 인벤토리 열었을 시 [E interation]상호작용 Ui 비활성화 완료.

**Comment by screat100** [comment]
완료
