### ISSUE TITLE
[5주차] 맵 상의 모든 적이 죽어야 문이 열리도록

### ISSUE THREAD

**Issue by screat100** [G-Man-git/PROJECT-SS-2#59]
현재는 문이 열려있는데,
문을 다 닫은 채로 시작하고
맵 상의 모든 적이 죽어야(=적이 없어야) 문이 열리도록 수정해주세요.

**Comment by grootnam** [comment]
완

**Comment by screat100** [comment]
빌드버전에서 오류 발생
- 특정 스테이지의 문 열리는 모습이 이상함
- 문이 아예 열려서 시작하는 스테이지도 존재

**Comment by screat100** [comment]
완료
