### ISSUE TITLE
적과 충돌하면 Y축으로 날려버림....

### ISSUE THREAD

**Issue by screat100** [G-Man-git/PROJECT-SS-2#6]
우선, 적이 플레이어를 감지하여 공격 애니메이션을 실행한 뒤에도 이 이슈가 발생하는지를 체크해야합니다. (아마 발생할 것이라고 예상됨)

**Comment by grootnam** [comment]
플레이어 Rigidbody y축 고정을 통해 y축으로 날아가는것을 방지.

**Comment by screat100** [comment]
@G-Man-git 
y축으로는 확 날아가지는 않는데, 추가 문제 발생하였음)
1. 적과 충돌한 이후 캐릭터의 movement 방향벡터가 이상해짐을 확인
(방향키 입력한것과 다르게 움직이는 속도가 느려지거나, 약간 대각선으로 꺾이는 등)
확인해보니 캐릭터가 가만히 있어도 일정 방향으로 계속 좌표가 이동되는 현상 확인

**Comment by screat100** [comment]
캐릭터의 RIGIDBODY에서 POSITION, ROTATION 고정을 설정해두지 않아서 생긴 문제였음...
각 씬에서 캐릭터들을 수정한 뒤 다음 커밋에 추가하겠음
